resource_group_name = "demorg1"
resource_group_location = "EastUS"
virtual_network_name = "demovn1"
address_space = ["10.0.0.0/16"]
public_ip_name = "demo_ip1"
vnet_subnet_name = "demo_subnet1"
network_interface_1= "demo_nic"
linuxvm_name = "demo-vm"
nsg_name = "demo-nsg"
loadb_name= "demolb"
count_value = 2
nat_list = [ "1000","1001" ]